/*
API Documentation

Source of truth and network automation platform

API version: 1.3.10b1 (1.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DeviceVirtualChassis struct for DeviceVirtualChassis
type DeviceVirtualChassis struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Url string `json:"url"`
	Master NestedDevice `json:"master"`
	MemberCount int32 `json:"member_count"`
	// Human friendly display value
	Display string `json:"display"`
}

// NewDeviceVirtualChassis instantiates a new DeviceVirtualChassis object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceVirtualChassis(id string, name string, url string, master NestedDevice, memberCount int32, display string) *DeviceVirtualChassis {
	this := DeviceVirtualChassis{}
	this.Id = id
	this.Name = name
	this.Url = url
	this.Master = master
	this.MemberCount = memberCount
	this.Display = display
	return &this
}

// NewDeviceVirtualChassisWithDefaults instantiates a new DeviceVirtualChassis object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceVirtualChassisWithDefaults() *DeviceVirtualChassis {
	this := DeviceVirtualChassis{}
	return &this
}

// GetId returns the Id field value
func (o *DeviceVirtualChassis) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeviceVirtualChassis) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeviceVirtualChassis) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DeviceVirtualChassis) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeviceVirtualChassis) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeviceVirtualChassis) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *DeviceVirtualChassis) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DeviceVirtualChassis) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DeviceVirtualChassis) SetUrl(v string) {
	o.Url = v
}

// GetMaster returns the Master field value
func (o *DeviceVirtualChassis) GetMaster() NestedDevice {
	if o == nil {
		var ret NestedDevice
		return ret
	}

	return o.Master
}

// GetMasterOk returns a tuple with the Master field value
// and a boolean to check if the value has been set.
func (o *DeviceVirtualChassis) GetMasterOk() (*NestedDevice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Master, true
}

// SetMaster sets field value
func (o *DeviceVirtualChassis) SetMaster(v NestedDevice) {
	o.Master = v
}

// GetMemberCount returns the MemberCount field value
func (o *DeviceVirtualChassis) GetMemberCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemberCount
}

// GetMemberCountOk returns a tuple with the MemberCount field value
// and a boolean to check if the value has been set.
func (o *DeviceVirtualChassis) GetMemberCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberCount, true
}

// SetMemberCount sets field value
func (o *DeviceVirtualChassis) SetMemberCount(v int32) {
	o.MemberCount = v
}

// GetDisplay returns the Display field value
func (o *DeviceVirtualChassis) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *DeviceVirtualChassis) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *DeviceVirtualChassis) SetDisplay(v string) {
	o.Display = v
}

func (o DeviceVirtualChassis) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["master"] = o.Master
	}
	if true {
		toSerialize["member_count"] = o.MemberCount
	}
	if true {
		toSerialize["display"] = o.Display
	}
	return json.Marshal(toSerialize)
}

type NullableDeviceVirtualChassis struct {
	value *DeviceVirtualChassis
	isSet bool
}

func (v NullableDeviceVirtualChassis) Get() *DeviceVirtualChassis {
	return v.value
}

func (v *NullableDeviceVirtualChassis) Set(val *DeviceVirtualChassis) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceVirtualChassis) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceVirtualChassis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceVirtualChassis(val *DeviceVirtualChassis) *NullableDeviceVirtualChassis {
	return &NullableDeviceVirtualChassis{value: val, isSet: true}
}

func (v NullableDeviceVirtualChassis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceVirtualChassis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


