/*
API Documentation

Source of truth and network automation platform

API version: 1.3.10b1 (1.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// NestedPowerPortTemplate Returns a nested representation of an object on read, but accepts either the nested representation or the primary key value on write operations.
type NestedPowerPortTemplate struct {
	Id string `json:"id"`
	Url string `json:"url"`
	Name string `json:"name"`
	// Human friendly display value
	Display string `json:"display"`
}

// NewNestedPowerPortTemplate instantiates a new NestedPowerPortTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedPowerPortTemplate(id string, url string, name string, display string) *NestedPowerPortTemplate {
	this := NestedPowerPortTemplate{}
	this.Id = id
	this.Url = url
	this.Name = name
	this.Display = display
	return &this
}

// NewNestedPowerPortTemplateWithDefaults instantiates a new NestedPowerPortTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedPowerPortTemplateWithDefaults() *NestedPowerPortTemplate {
	this := NestedPowerPortTemplate{}
	return &this
}

// GetId returns the Id field value
func (o *NestedPowerPortTemplate) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NestedPowerPortTemplate) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NestedPowerPortTemplate) SetId(v string) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *NestedPowerPortTemplate) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *NestedPowerPortTemplate) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *NestedPowerPortTemplate) SetUrl(v string) {
	o.Url = v
}

// GetName returns the Name field value
func (o *NestedPowerPortTemplate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NestedPowerPortTemplate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NestedPowerPortTemplate) SetName(v string) {
	o.Name = v
}

// GetDisplay returns the Display field value
func (o *NestedPowerPortTemplate) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *NestedPowerPortTemplate) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *NestedPowerPortTemplate) SetDisplay(v string) {
	o.Display = v
}

func (o NestedPowerPortTemplate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["display"] = o.Display
	}
	return json.Marshal(toSerialize)
}

type NullableNestedPowerPortTemplate struct {
	value *NestedPowerPortTemplate
	isSet bool
}

func (v NullableNestedPowerPortTemplate) Get() *NestedPowerPortTemplate {
	return v.value
}

func (v *NullableNestedPowerPortTemplate) Set(val *NestedPowerPortTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedPowerPortTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedPowerPortTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedPowerPortTemplate(val *NestedPowerPortTemplate) *NullableNestedPowerPortTemplate {
	return &NullableNestedPowerPortTemplate{value: val, isSet: true}
}

func (v NullableNestedPowerPortTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedPowerPortTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


