/*
API Documentation

Source of truth and network automation platform

API version: 1.3.10b1 (1.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// NestedPlatform Returns a nested representation of an object on read, but accepts either the nested representation or the primary key value on write operations.
type NestedPlatform struct {
	Id string `json:"id"`
	Url string `json:"url"`
	Name string `json:"name"`
	Slug *string `json:"slug,omitempty"`
	DeviceCount int32 `json:"device_count"`
	VirtualmachineCount int32 `json:"virtualmachine_count"`
	// Human friendly display value
	Display string `json:"display"`
}

// NewNestedPlatform instantiates a new NestedPlatform object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedPlatform(id string, url string, name string, deviceCount int32, virtualmachineCount int32, display string) *NestedPlatform {
	this := NestedPlatform{}
	this.Id = id
	this.Url = url
	this.Name = name
	this.DeviceCount = deviceCount
	this.VirtualmachineCount = virtualmachineCount
	this.Display = display
	return &this
}

// NewNestedPlatformWithDefaults instantiates a new NestedPlatform object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedPlatformWithDefaults() *NestedPlatform {
	this := NestedPlatform{}
	return &this
}

// GetId returns the Id field value
func (o *NestedPlatform) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NestedPlatform) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NestedPlatform) SetId(v string) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *NestedPlatform) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *NestedPlatform) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *NestedPlatform) SetUrl(v string) {
	o.Url = v
}

// GetName returns the Name field value
func (o *NestedPlatform) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NestedPlatform) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NestedPlatform) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *NestedPlatform) GetSlug() string {
	if o == nil || o.Slug == nil {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedPlatform) GetSlugOk() (*string, bool) {
	if o == nil || o.Slug == nil {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *NestedPlatform) HasSlug() bool {
	if o != nil && o.Slug != nil {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *NestedPlatform) SetSlug(v string) {
	o.Slug = &v
}

// GetDeviceCount returns the DeviceCount field value
func (o *NestedPlatform) GetDeviceCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeviceCount
}

// GetDeviceCountOk returns a tuple with the DeviceCount field value
// and a boolean to check if the value has been set.
func (o *NestedPlatform) GetDeviceCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceCount, true
}

// SetDeviceCount sets field value
func (o *NestedPlatform) SetDeviceCount(v int32) {
	o.DeviceCount = v
}

// GetVirtualmachineCount returns the VirtualmachineCount field value
func (o *NestedPlatform) GetVirtualmachineCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VirtualmachineCount
}

// GetVirtualmachineCountOk returns a tuple with the VirtualmachineCount field value
// and a boolean to check if the value has been set.
func (o *NestedPlatform) GetVirtualmachineCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VirtualmachineCount, true
}

// SetVirtualmachineCount sets field value
func (o *NestedPlatform) SetVirtualmachineCount(v int32) {
	o.VirtualmachineCount = v
}

// GetDisplay returns the Display field value
func (o *NestedPlatform) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *NestedPlatform) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *NestedPlatform) SetDisplay(v string) {
	o.Display = v
}

func (o NestedPlatform) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Slug != nil {
		toSerialize["slug"] = o.Slug
	}
	if true {
		toSerialize["device_count"] = o.DeviceCount
	}
	if true {
		toSerialize["virtualmachine_count"] = o.VirtualmachineCount
	}
	if true {
		toSerialize["display"] = o.Display
	}
	return json.Marshal(toSerialize)
}

type NullableNestedPlatform struct {
	value *NestedPlatform
	isSet bool
}

func (v NullableNestedPlatform) Get() *NestedPlatform {
	return v.value
}

func (v *NullableNestedPlatform) Set(val *NestedPlatform) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedPlatform) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedPlatform) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedPlatform(val *NestedPlatform) *NullableNestedPlatform {
	return &NullableNestedPlatform{value: val, isSet: true}
}

func (v NullableNestedPlatform) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedPlatform) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


