/*
API Documentation

Source of truth and network automation platform

API version: 1.3.7 (1.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ConfigContextDeviceTypesInnerManufacturer struct for ConfigContextDeviceTypesInnerManufacturer
type ConfigContextDeviceTypesInnerManufacturer struct {
	Id string `json:"id"`
	Url string `json:"url"`
	Name string `json:"name"`
	Slug *string `json:"slug,omitempty"`
	DevicetypeCount int32 `json:"devicetype_count"`
	// Human friendly display value
	Display string `json:"display"`
}

// NewConfigContextDeviceTypesInnerManufacturer instantiates a new ConfigContextDeviceTypesInnerManufacturer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigContextDeviceTypesInnerManufacturer(id string, url string, name string, devicetypeCount int32, display string) *ConfigContextDeviceTypesInnerManufacturer {
	this := ConfigContextDeviceTypesInnerManufacturer{}
	this.Id = id
	this.Url = url
	this.Name = name
	this.DevicetypeCount = devicetypeCount
	this.Display = display
	return &this
}

// NewConfigContextDeviceTypesInnerManufacturerWithDefaults instantiates a new ConfigContextDeviceTypesInnerManufacturer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigContextDeviceTypesInnerManufacturerWithDefaults() *ConfigContextDeviceTypesInnerManufacturer {
	this := ConfigContextDeviceTypesInnerManufacturer{}
	return &this
}

// GetId returns the Id field value
func (o *ConfigContextDeviceTypesInnerManufacturer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConfigContextDeviceTypesInnerManufacturer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConfigContextDeviceTypesInnerManufacturer) SetId(v string) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *ConfigContextDeviceTypesInnerManufacturer) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ConfigContextDeviceTypesInnerManufacturer) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ConfigContextDeviceTypesInnerManufacturer) SetUrl(v string) {
	o.Url = v
}

// GetName returns the Name field value
func (o *ConfigContextDeviceTypesInnerManufacturer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConfigContextDeviceTypesInnerManufacturer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConfigContextDeviceTypesInnerManufacturer) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *ConfigContextDeviceTypesInnerManufacturer) GetSlug() string {
	if o == nil || o.Slug == nil {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigContextDeviceTypesInnerManufacturer) GetSlugOk() (*string, bool) {
	if o == nil || o.Slug == nil {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *ConfigContextDeviceTypesInnerManufacturer) HasSlug() bool {
	if o != nil && o.Slug != nil {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *ConfigContextDeviceTypesInnerManufacturer) SetSlug(v string) {
	o.Slug = &v
}

// GetDevicetypeCount returns the DevicetypeCount field value
func (o *ConfigContextDeviceTypesInnerManufacturer) GetDevicetypeCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DevicetypeCount
}

// GetDevicetypeCountOk returns a tuple with the DevicetypeCount field value
// and a boolean to check if the value has been set.
func (o *ConfigContextDeviceTypesInnerManufacturer) GetDevicetypeCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DevicetypeCount, true
}

// SetDevicetypeCount sets field value
func (o *ConfigContextDeviceTypesInnerManufacturer) SetDevicetypeCount(v int32) {
	o.DevicetypeCount = v
}

// GetDisplay returns the Display field value
func (o *ConfigContextDeviceTypesInnerManufacturer) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *ConfigContextDeviceTypesInnerManufacturer) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *ConfigContextDeviceTypesInnerManufacturer) SetDisplay(v string) {
	o.Display = v
}

func (o ConfigContextDeviceTypesInnerManufacturer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Slug != nil {
		toSerialize["slug"] = o.Slug
	}
	if true {
		toSerialize["devicetype_count"] = o.DevicetypeCount
	}
	if true {
		toSerialize["display"] = o.Display
	}
	return json.Marshal(toSerialize)
}

type NullableConfigContextDeviceTypesInnerManufacturer struct {
	value *ConfigContextDeviceTypesInnerManufacturer
	isSet bool
}

func (v NullableConfigContextDeviceTypesInnerManufacturer) Get() *ConfigContextDeviceTypesInnerManufacturer {
	return v.value
}

func (v *NullableConfigContextDeviceTypesInnerManufacturer) Set(val *ConfigContextDeviceTypesInnerManufacturer) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigContextDeviceTypesInnerManufacturer) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigContextDeviceTypesInnerManufacturer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigContextDeviceTypesInnerManufacturer(val *ConfigContextDeviceTypesInnerManufacturer) *NullableConfigContextDeviceTypesInnerManufacturer {
	return &NullableConfigContextDeviceTypesInnerManufacturer{value: val, isSet: true}
}

func (v NullableConfigContextDeviceTypesInnerManufacturer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigContextDeviceTypesInnerManufacturer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


